Add expected input format to RTC custom time prompts
OPEnSLab-OSU/Loom pull request #184
Opened 2022-03-29 16:50 UTC by kurtjd

Very slight modification to RTC.cpp where `set_rtc_to_computer_time()` displays the expected input format when prompting for year, month, and day. This is to prevent confusion, for example, as to whether month is expecting the actual month name (March) or a month number (3).

2022-03-29 21:40 UTC, WL-Richards requested changes
The year is the only fix, needed

2022-03-29 21:40 UTC, WL-Richards commented on src/RTC/RTC.cpp
> +	LPrintln("Enter the Year (20xx)");
Change to examples instead of (20xx), confusing for users

2022-03-29 21:40 UTC, WL-Richards commented on src/RTC/RTC.cpp
> +	LPrintln("Enter the Day (1 ~ 31)");
The rest of these look good!

2022-03-30 18:48 UTC, kurtjd commented
Made changes to year prompt to use 4 digit example.

2022-03-31 21:03 UTC, merged